version: "3.6"

services:
  postgres:
    image: postgres:11.5-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: opendatacubepassword
    restart: always

  waterbodies:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
      - AWS_NO_SIGN_REQUEST=YES
    volumes:
      - .:/code
    depends_on:
      - postgres

  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
