version: "3.6"

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    expose:
      - 5432
    restart: always

  waterbodies:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=opendatacube
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=opendatacube
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=${ODC_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${ODC_SECRET_KEY}
    volumes:
      - .:/code
    depends_on:
      - postgres
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 180 ; done"]

  index:
     image: opendatacube/datacube-index:0.0.13
     environment:
        - DB_HOSTNAME=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=opendatacubepassword
        - DB_DATABASE=postgres
        - DB_PORT=5432
        - AWS_DEFAULT_REGION=ap-southeast-2
     depends_on:
        - postgres
     entrypoint: bash -c 'sleep infinity'
