name: dea-waterbodies-env
channels:
  - defaults
dependencies:
  - numpy
  - geopandas
  - gdal
  - pip:
    - datacube
    - python-geohash
    - rioxarray
    - fsspec==0.8.0
    - rasterstats
    - --extra-index-url="https://packages.dea.ga.gov.au"
    - odc-apps-dc-tools
