name: dea-waterbodies-env
channels:
  - defaults
dependencies:
  - numpy
  - geopandas
  - gdal
  - pip:
    - python-geohash
    - rioxarray
    - datacube
    - git+https://github.com/GeoscienceAustralia/dea-notebooks.git#subdirectory=Tools
