name: Push

on:
  push:
    branches:
      - stable
    paths:
      - 'dea_waterbodies/**'
      - '.github/workflows/push.yml'
      - 'Dockerfile'

  release:
    types: [created, edited]

env:
  IMAGE_NAME: GeoscienceAustralia/dea-waterbodies

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get tag for this build if it exists
      if: github.event_name == 'release'
      run: |
        echo "RELEASE=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
    - name: Build and Push semver tagged Docker Image for Release
      uses: whoan/docker-build-with-cache-action@v4
      if: github.event_name == 'release'
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: ${{ env.RELEASE }}
    - name: Run Trivy vulnerability scanner for Release
      uses: aquasecurity/trivy-action@master
      if: github.event_name == 'release'
      with:
        image-ref: 'docker.io/GeoscienceAustralia/dea-waterbodies:${{ env.RELEASE }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Get git commit hash for push to main
      if: github.event_name != 'release'
      run: |
        git fetch --all --tags
        echo "RELEASE=$(git describe --tags)" >> $GITHUB_ENV
    - name: Build and Push unstable Docker Image for push to main
      uses: whoan/docker-build-with-cache-action@v4
      if: github.event_name != 'release'
      with:
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: latest,${{ env.GITHASH }}
    - name: Run Trivy vulnerability scanner for push to main
      uses: aquasecurity/trivy-action@master
      if: github.event_name != 'release'
      with:
        image-ref: 'docker.io/GeoscienceAustralia/dea-waterbodies:${{ env.GITHASH }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
